### ISSUE TITLE
npm request paketi ile uyumsuzluk

### ISSUE THREAD

**Issue by emehmet** [selmansamet/node-paytr#2]
Merhabalar,
Öncelikle emeğin için teşekkürler.
npm request paketi kod yapısı değişmiş. istek atılamıyor. first parameter must be string hatası veriyor.
Ben şu şekle çevirdim paytr.js dosyasında ;
request.post({url:options.uri,formData:options.formData}, function (error, response, body) {

bu veya diğer alternatiflerine güncelleyebilir misin?

**Comment by sametcodes** [comment]
Selamlar, issue için teşekkürler.

Yüklediğin request versiyonunu yazabilir misin? Kontrol ettikten sonra düzenlemeyi yapacağım.

**Comment by emehmet** [comment]
Merhabalar,
request@2.88.0
npm ile node-paytr yi yükleyince gelen version. sanırım şuanda son version.

**Comment by sametcodes** [comment]
`request(params, ...){` şeklinde çalışıyordu bende, fakat dökümanda `request.post(params, ...)` şeklinde örneklerin daha fazla olduğunu gördüğüm için dediğin şekilde denedim ve düzenlemeyi yaptım. Yeni versiyonu npm üzerinden alabilirsin.

Katkı için teşekkürler :rocket:
