### ISSUE TITLE
Possiblities to integrate with Rest API?

### ISSUE THREAD

**Issue by prakharAgrawalTed** [selmansamet/node-paytr#4]
Hi, Is this possible to integrate Paytr Payment gateway with Rest API (without iframe)?

**Comment by sametcodes** [comment]
This package works only get iframe token and the callbacks.

I'm not sure. I know that PayTR works only with iframe token. I just looked at the API documents and I didn't see any different method. You should ask them.

**Comment by sametcodes** [comment]
It's been two years, and it seems PayTR made public some other APIs, such as [Direct API](https://dev.paytr.com/en/direkt-api) and [Transfer/EFT iFrame API](https://dev.paytr.com/en/havale-eft-iframe-api). I'm planning to widen the module for these as well.
